# **19CSE305: MACHINE LEARNING LAB 2**

ROLL NUMBER: CB.EN.U4CSE20465 

In [56]:
import pandas as pd
import numpy as np
import sys

## Python Basic Exercises

1. Get the values P,t,R from user and calculate compound interest. Formula to calculate compound interest annually is given by: 
        
        
        a) A = P(1+R/100)^t
        b) CI = A – P
        c) Input : Principle, Time, Rate
        d) Output : Compound Interest
2. Given a list of strings (Entered by the user), write program to get a percentage share of each word in the strings list.
        
        percentage = (Occurrence of a word / Total words) * 100
3. Check if  the binary representation of a number is Palindrome or not. Given an integer ‘n’ (entered by the user), write a Python function that returns true if binary representation of 'x' is palindrome and false if not.
4. Write a program to check if all digits of a number divide it. Given a number n (entered by the user), find whether all digits of n divide it or not.
5. Given a list of numbers (entered by the user), write a program to find the second largest number in that list.
        
        Input: [1, 2, 3, 4 ,5]
        Output: 4

In [62]:
# Question 1

def compundInterest(P, T, R):
    #A = P(1+R/100)^t
    a = P * ((1+(R/100))**T)

    return a - P

P = int(input("Enter P "))
T = int(input("Enter T "))
R = int(input("Enter R "))

print(f'Compound interst is {compundInterest(P, T, R)}')


Compound interst is 730.7999999999993


In [ ]:
# Question 2

str = input("Enter the string ")

words = str.split(' ')
wordMap = {}
n = 0

for i in words:
    if i not in wordMap:
        wordMap[i] = 0
    wordMap[i] += 1
    n += 1

for word in wordMap:
    wordMap[word] = (wordMap[word]/n)*100

print(wordMap)

{'word': 40.0, 'string': 20.0, 'press': 20.0, 'confirm': 20.0}


In [ ]:
# Question 3:

num = int(input())

bin = []

while(num):
    bin.append(num%2)
    num //= 2

print(bin)
print(bin == bin[::-1])

[1, 0, 1]
True


In [ ]:
# Question 4:

dummy = input()

digits = []
num = int(dummy)

boo = True

for i in dummy:
    if int(i) != 0 and num%int(i) != 0:
        boo = False
        break

print("Number is divisible by all of its digits") if boo else print("Number is not divisible by all of its digits")

Number is divisible by all of its digits


In [ ]:
nums = input().split() 

for i in range(len(nums)):
    nums[i] = int(nums[i])

nums.sort()
print("Second largest number is {}".format(nums[-2]))

[5, 6, 34, 36, 42, 45, 45, 64]
Second largest number is 45


## Numpy Basic Exercises

1. Create a 3D array of shape 4X5X2 that contains random decimal numbers between 1 and 10.
2. Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3. Given a NumPy array of temperature values, convert the values of Centigrade degrees into Fahrenheit degrees. 
4. Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5. Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array

In [47]:
np.random.randint(10, size=(4, 5, 2))

array([[[8, 7],
        [8, 1],
        [4, 2],
        [7, 1],
        [5, 9]],

       [[9, 9],
        [9, 5],
        [9, 0],
        [2, 0],
        [6, 8]],

       [[9, 2],
        [2, 1],
        [7, 0],
        [9, 9],
        [7, 7]],

       [[2, 1],
        [3, 7],
        [2, 0],
        [4, 0],
        [5, 2]]])

In [39]:
np.random.randint(10, size=20).reshape(2, 10)

array([[9, 6, 8, 4, 9, 0, 3, 1, 4, 8],
       [5, 2, 7, 6, 9, 1, 3, 6, 9, 5]])

In [46]:
cels = np.random.randint(100, size=20)
print((cels*1.8)+32)


[201.2 129.2  57.2 188.6  73.4 156.2 156.2 161.6  41.  192.2 111.2 122.
 114.8 140.  116.6 123.8  33.8 177.8 111.2  75.2]


In [61]:
ip = np.random.randint(10, size=(4, 5, 2))

print(f'Number of dimensions: {len(ip.shape)}')

eleNum = 1
for i in ip.shape:
    eleNum *= i

print(f'Number of elements: {eleNum}')

sys.getsizeof(i)

Number of dimensions: 3
Number of elements: 40


28

In [55]:
mat =np.random.randint(10, size=(3, 4))

print(mat)

print(mat[0, 1], mat[1, 2])

[[7 7 5 6]
 [0 6 4 2]
 [6 0 7 6]]
7 4
