In [1]:
import numpy as np

In [5]:
a = np.array([69]*9)
print(type(a))
print(a)

print(f'shape : {a.shape}')

<class 'numpy.ndarray'>
[69 69 69 69 69 69 69 69 69]
shape : (9,)


In [7]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Shape: {b.shape}')

print(f' {b[2, 2]} ')

Shape: (3, 3)
 9 


### numpy arrays creation funcitons:

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full((6,9), 69)

array([[69, 69, 69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69, 69, 69]])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [14]:
np.random.random((6,9))

array([[0.364691  , 0.15858374, 0.31675918, 0.34047022, 0.76587419,
        0.39313244, 0.19044415, 0.89010335, 0.03217791],
       [0.91666171, 0.61581531, 0.57629554, 0.4392139 , 0.49983118,
        0.16028605, 0.8814708 , 0.12691503, 0.9389924 ],
       [0.96008623, 0.50892335, 0.015204  , 0.6267776 , 0.22620663,
        0.63048217, 0.41379349, 0.46796306, 0.82036574],
       [0.94532957, 0.78314205, 0.03960865, 0.22067781, 0.5830784 ,
        0.4519468 , 0.74084821, 0.03645706, 0.95600547],
       [0.52992314, 0.64687793, 0.58991902, 0.24462961, 0.06104016,
        0.69734714, 0.52789728, 0.71049761, 0.24752937],
       [0.15535532, 0.68970389, 0.63201955, 0.23156618, 0.62016229,
        0.1064019 , 0.80114746, 0.06285705, 0.93120238]])

#### Array slicing

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a[:2, 1:]

array([[2, 3],
       [5, 6]])

### Array maths

In [19]:
x = np.array([[6, 9], [9, 6]], dtype=int)
y = np.array([[9, 6], [6, 9]], dtype=int)

In [22]:
x+y

array([[15, 15],
       [15, 15]])

In [23]:
np.add(x, y)

array([[15, 15],
       [15, 15]])

In [24]:
np.multiply(x, y)

array([[54, 54],
       [54, 54]])

In [25]:
np.sqrt(x)

array([[2.44948974, 3.        ],
       [3.        , 2.44948974]])